### ISSUE TITLE
Don't report last stops in trip

### ISSUE THREAD

**Issue by dfaulken** [umts/bojangles#13]
As an example, let's say we're monitoring Studio Arts Building.

The 45 has a trip inbound from Belchertown Center with headsign UMass, ending at Studio Arts Building; and a trip with headsign Bus Garage via Compsci, starting at Studio Arts Building.

The current logic will expect to see both departures at the same time, which is incorrect. However because our times are stored in a CSV and not in a relational database, it seems like it would be difficult to not cache departures which are the last stop in a particular trip.

**Comment by sherson** [comment]
Cool
