### ISSUE TITLE
Don't store SAB identifiers in multiple places

### ISSUE THREAD

**Issue by dfaulken** [umts/bojangles#17]
Namely [here](https://github.com/umts/bojangles/blob/master/lib/bojangles.rb#L21) and [here](https://github.com/umts/bojangles/blob/master/lib/gtfs_parser.rb#L9).

**Comment by mboneil10** [comment]
@dfaulken why is this happening? Shouldn't SAB be in stops.txt?

**Comment by dfaulken** [comment]
I don't understand the question. It is, there's no problem with retrieving it. The issue is that there's no reason to store both its name and its ID as constants. We can get its ID from its name in stops.txt, as you say.
